"""A small, deterministic stand-in for data/kyc_aml.db.

The real seed is regenerated by other people at any time (transaction IDs change meaning, typologies are added), so
unit tests must not depend on it. This builds a tiny database with the same schema columns the seed adapter reads
and the attack patterns the adapter has to handle:

  card ring     four customers hit one merchant through ONE shared device within minutes (micro-charges, then a drain)
  scam burst    five customers pay the same brand-new payee within seconds, then a second payee two days later
  takeover      a domestic purchase followed by an international wire from a new device in another country
  landlord      twelve customers pay one landlord at the same instant (a synchronized burst that is NOT suspicious)
"""

import sqlite3
from datetime import datetime, timedelta

HOME = "CA"
BASE = datetime(2026, 9, 1, 9, 0, 0)

# ids the tests refer to
RING_FIRST_PROBE = "TXN-RA1P1"
RING_DRAIN_FIRST = "TXN-RA1D"
RING_DRAIN_LAST = "TXN-RA4D"
SCAM_FIRST = "TXN-AP1T1"
SCAM_LATE = "TXN-AP5T2"
TAKEOVER = "TXN-AT1W"
LANDLORD_LAST = "TXN-LL12"
LANDLORD_FIRST = "TXN-LL01"
RING_DEVICE = "DEV-BOTNET-CLONE-441"  # deliberately names the fraud, to prove device ids are pseudonymised

SCHEMA = """
CREATE TABLE customers (customer_id TEXT, device_primary_id TEXT, primary_ip_country TEXT,
    declared_expected_max_single_tx_usd REAL, declared_expected_monthly_turnover_usd REAL);
CREATE TABLE transactions (transaction_id TEXT, customer_id TEXT, timestamp TEXT, transaction_type TEXT, direction TEXT,
    amount_usd REAL, currency TEXT, counterparty_name TEXT, counterparty_country TEXT, counterparty_category TEXT,
    channel TEXT, reference_narrative TEXT, device_id TEXT, ip_country TEXT, auth_status TEXT, card_entry_mode TEXT,
    is_new_payee INTEGER, payee_first_seen_hours REAL, is_fraud_synthetic INTEGER, fraud_typology_tag TEXT,
    is_suspicious_synthetic INTEGER, synthetic_typology_tag TEXT);
CREATE TABLE alerts (customer_id TEXT, rule_id TEXT, severity TEXT, supporting_transaction_ids TEXT);
"""


class _Builder:
    def __init__(self, conn):
        self.conn = conn
        self.n = 0

    def customer(self, cid, device, declared_max=2600.0):
        self.conn.execute("INSERT INTO customers VALUES (?,?,?,?,?)", (cid, device, HOME, declared_max, 4000.0))

    def tx(self, tid, cid, when, kind, direction, amount, name, category="RETAILER", channel="WEB_PORTAL", device=None,
           ip=None, auth="AUTHORIZED", entry=None, new_payee=0, first_seen=None, fraud=None, country="US"):
        self.conn.execute(
            "INSERT INTO transactions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (tid, cid, when.isoformat(), kind, direction, amount, "USD", name, country, category, channel,
             "reference text", device, ip, auth, entry, new_payee, first_seen, 1 if fraud else 0, fraud, 0, None))

    def alert(self, cid, rule, severity, tx_ids):
        import json
        self.conn.execute("INSERT INTO alerts VALUES (?,?,?,?)", (cid, rule, severity, json.dumps(tx_ids)))

    def history(self, cid, device, days=30, with_ach=False):
        """Ordinary behaviour: a purchase a day on the customer's own device, plus a salary credit."""
        for d in range(days, 0, -1):
            self.n += 1
            self.tx(f"TXN-H{self.n:05d}", cid, BASE - timedelta(days=d), "POS_PURCHASE", "OUTBOUND", 20 + (d * 7) % 60,
                    "Neighbourhood Grocer", device=device, ip=HOME, channel="MOBILE_APP")
        self.n += 1
        self.tx(f"TXN-H{self.n:05d}", cid, BASE - timedelta(days=15), "SALARY_CREDIT", "INBOUND", 3000.0, "Employer Inc",
                category="EMPLOYER", channel="ACH", country=HOME)


def build_fixture(path):
    conn = sqlite3.connect(path)
    conn.executescript(SCHEMA)
    b = _Builder(conn)

    # card ring: one shared device, minutes apart
    ring_t0 = datetime(2026, 9, 5, 3, 12, 0)
    for i in range(1, 5):
        cid, dev = f"CUST-9100{i}", f"DEV-OWN-A{i}"
        b.customer(cid, dev)
        b.history(cid, dev)
        t = ring_t0 + timedelta(seconds=30 * i)
        kw = dict(device=RING_DEVICE, ip="NL", entry="CNP_ECOMMERCE", fraud="CARD_TESTING_MICRO_PROBE")
        b.tx(f"TXN-RA{i}P1", cid, t, "ONLINE_PURCHASE", "OUTBOUND", 0.89, "Digital Test Service 1", **kw)
        b.tx(f"TXN-RA{i}P2", cid, t + timedelta(minutes=4), "ONLINE_PURCHASE", "OUTBOUND", 1.45, "Digital Test Service 2", **kw)
        b.tx(f"TXN-RA{i}D", cid, t + timedelta(minutes=18), "ONLINE_PURCHASE", "OUTBOUND", 4500.0 + i * 10,
             "Luxe Electronics Direct", device=RING_DEVICE, ip="NL", entry="CNP_ECOMMERCE", auth="DECLINED_SUSPECTED_FRAUD",
             fraud="CARD_FRAUD_HIGH_VALUE_DRAIN", country="HK")
        b.alert(cid, "FR-02", "HIGH", [f"TXN-RA{i}P1", f"TXN-RA{i}P2", f"TXN-RA{i}D"])

    # scam burst: brand-new payees, same instant, repeated two days later
    for i in range(1, 6):
        cid, dev = f"CUST-9200{i}", f"DEV-OWN-B{i}"
        b.customer(cid, dev, declared_max=3000.0)
        b.history(cid, dev)
        common = dict(kind="P2P_TRANSFER_OUT", direction="OUTBOUND", category="INDIVIDUAL", channel="MOBILE_APP", device=dev,
                      ip=HOME, new_payee=1, first_seen=0.5, fraud="APP_INVESTMENT_SCAM", country="GB")
        b.tx(f"TXN-AP{i}T1", cid, datetime(2026, 9, 17, 0, 42, i), amount=6500.0, name="Alpha Pool Ltd", **common)
        b.tx(f"TXN-AP{i}T2", cid, datetime(2026, 9, 19, 0, 42, i), amount=9800.0, name="Escrow Ltd", **common)
        b.alert(cid, "FR-03", "HIGH", [f"TXN-AP{i}T2"])

    # account takeover: normal purchase at home, then a wire from a new device in another country
    b.customer("CUST-93001", "DEV-OWN-C1", declared_max=5000.0)
    b.history("CUST-93001", "DEV-OWN-C1")
    day = datetime(2026, 9, 19, 14, 5, 0)
    b.tx("TXN-AT1P", "CUST-93001", day, "POS_PURCHASE", "OUTBOUND", 42.0, "Neighbourhood Grocer", device="DEV-OWN-C1", ip=HOME,
         channel="MOBILE_APP")
    b.tx("TXN-AT1W", "CUST-93001", day + timedelta(minutes=40), "INTERNATIONAL_WIRE_OUT", "OUTBOUND", 12000.0,
         "FastPay Clearing Ltd", category="INDIVIDUAL", channel="SWIFT", device="DEV-UNKNOWN-ATTACKER", ip="NG",
         new_payee=1, first_seen=0.2, fraud="ATO_IMPOSSIBLE_TRAVEL", country="NG")

    # landlord paid by everyone at the same instant (ACH: no device telemetry)
    for i in range(1, 13):
        cid, dev = f"CUST-9400{i:02d}", f"DEV-OWN-L{i:02d}"
        b.customer(cid, dev, declared_max=40000.0)
        b.history(cid, dev)
        b.tx(f"TXN-LL{i:02d}", cid, datetime(2026, 9, 10, 9, 0, i), "ACH_WITHDRAWAL", "OUTBOUND", 30000.0 + i * 100,
             "Big City Landlord", category="UTILITY", channel="ACH", country="CH")
    b.alert("CUST-940001", "TM-04", "HIGH", ["TXN-LL01"])  # one flagged payer out of twelve: nowhere near a meaningful share

    # ordinary customers with larger-than-usual spending but nothing suspicious
    for i in range(1, 6):
        cid, dev = f"CUST-9500{i}", f"DEV-OWN-D{i}"
        b.customer(cid, dev)
        b.history(cid, dev)
        b.tx(f"TXN-CL{i}", cid, datetime(2026, 9, 12, 12, i, 0), "POS_PURCHASE", "OUTBOUND", 900.0 + i, "Appliance Store",
             channel="MOBILE_APP", device=dev, ip=HOME)

    # a realistic population: many ordinary customers shop at the same merchants, so a few flagged payers are a tiny share
    for i in range(1, 61):
        cid, dev = f"CUST-9600{i:02d}", f"DEV-OWN-F{i:02d}"
        b.customer(cid, dev)
        b.history(cid, dev, days=6)

    conn.commit()
    conn.close()
    return path
